import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Header from '../components/Header/Header'
import Benefits from '../components/Benefits/Benefits'
import Employment from '../components/Employment/Employment'
import Reviews from '../components/Reviews/Reviews'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Benefits />
      <Employment />
      <Reviews rating={4} />
      <Footer />
    </div>
  )
}
